name: null
channel_priority: strict

channels:
#  - blazingsql
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
#  - blazingsql>=0.15
  - nodejs
  - cudatoolkit=11.*
  - jupyterlab=3.*
  - jupyterlab-git>=0.30
  - pip=21.*
  - pip:
    - -r requirements.txt
  - python=3.8
  - rapids=21.*

